// <auto-generated />
using Lab4Real;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab4Real.Migrations
{
    [DbContext(typeof(EquationContext))]
    [Migration("20240109161155_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Lab4Real.SolutionsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("A")
                        .HasColumnType("REAL");

                    b.Property<double>("B")
                        .HasColumnType("REAL");

                    b.Property<double>("C")
                        .HasColumnType("REAL");

                    b.Property<int>("NumberOfRoots")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Root1")
                        .HasColumnType("REAL");

                    b.Property<double>("Root2")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SolutionsData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
